version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: changeit
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    networks:
      - dev_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pchangeit"]
      timeout: 20s
      retries: 10
  liferay:
    container_name: liferay
    image: liferay/dxp:7.2.10.1
    depends_on: 
      - mysql
      - elasticsearch
    environment: 
      - LIFERAY_JPDA_ENABLED=false
      - LIFERAY_JVM_OPTS=-Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=8099 -Dcom.sun.management.jmxremote.ssl=false -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
    ports:
      - 8080:8080
      - 11311:11311
      - 8000:8000
      - 8099:8099
    volumes:
      - ./liferay:/mnt/liferay
      - ./liferay/deploy:/mnt/liferay/deploy
    networks:
      - dev_network
    healthcheck:
      test: ["CMD", "curl -fsS 'http://localhost:8080/c/portal/layout' || exit 1"]
      interval: 1m
      timeout: 1m
      start_period: 3m
      retries: 5
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    networks:
      - dev_network
    environment:
      - cluster.name=LiferayElasticsearchCluster
      - node.name=LiferayNode
      - bootstrap.memory_lock=true
      - node.master=true
      - node.data=true
      - network.host=elasticsearch
      - network.bind_host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,X-User
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 'http://localhost:9200/_cluster/health' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
  fakesmtp:
    container_name: fakesmtp
    image: munkyboy/fakesmtp
    volumes:
      - ./fakemail:/var/mail
    networks: 
      - dev_network
  jenkins:
    container_name: jenkins
    build: ./jenkins/build
    volumes: 
      - ./jenkins/home:/var/jenkins_home
      - ./jenkins/security.groovy:/usr/share/jenkins/ref/init.groovy.d/security.groovy
      - ./liferay/deploy:/var/liferay_deploy
    environment: 
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - "8090:8080"
      - "50000:50000"
networks:
  dev_network: